[versions]
agp = "8.12.0"
kotlin = "2.2.10"
doordeck-sdk = "0.101.0"

[libraries]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]
